### ISSUE TITLE
Build error with GCC 6.2.0

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/mame#32]
It will fail if you build with gcc 6.2.0, tested on ubuntu 16.10, any architecture

```
/usr/include/c++/6/bits/unique_ptr.h:614:6: error: no matching function for call to ‘swap(const z8002_device::Z8000_exec*&, z8002_device::Z8000_exec*&)’
  swap(std::get<0>(_M_t), __p);
  ~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

https://launchpadlibrarian.net/321934418/buildlog_ubuntu-yakkety-amd64.libretro-mame_1%3A0.185-r201705311219-9f8a36a-57~ubuntu16.10.1_BUILDING.txt.gz

**Comment by r-type** [comment]
there are some report at sdlmame forum about libstdc++ issue 
Vas Crabb seem to point at some interesting things.
maybe related to your issue.

http://forums.bannister.org//ubbthreads.php?ubb=showflat&Number=69633&page=36

**Comment by r-type** [comment]
i miss this one too.
https://github.com/mamedev/mame/issues/2347

**Comment by r-type** [comment]
If upstream closed this one , i think we can close it too.

**Comment by sergiobenrocha2** [comment]
Yeah, not really a big deal, thanks!

**Comment by r-type** [comment]
I've build polepos driver (z8000) ,it failed as expected with 6.2 but build fine with 7.1.
